[package]
authors = ["Michael Aaron Murphy <mmstickman@gmail.com>"]
name = "fontfinder"
description = "Font Finder Library"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/mmstick/fontfinder"
version = "1.4.1"

[workspace]
members = ["gtk"]

[dependencies]
failure = "0.1"
failure_derive = "0.1"
horrorshow = "0.6"
itertools = "0.7"
lazy_static = "1.0"
reqwest = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
